### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by Tron-Creeper2** [versaceLORD/virtual-auto-clicker#12]
**Hi, is there any way to put it in Roblox? I tried `startautoclicker "Roblox" -1200,770 300000 SPFS` but all it did was put out an error.
maybe it was cause I had it on my 2nd monitor?**

> VAC >> Something went wrong when trying to start the autoclicker!
>  System.Exception: There was no process named Roblox, no auto clickerstarted.
>    at VirtualAutoClicker.AutoClicker.Init() in C:\Projects\virtual-auto-clicker\src\VirtualAutoClicker\AutoClicker.cs:line 52
>    at VirtualAutoClicker.Commands.StartAutoClicker.Start(String proposedAcName, String processName, Coordinates coordinates, Int32 interval) in C:\Projects\virtual-auto-clicker\src\VirtualAutoClicker\Commands\StartAutoClicker.cs:line 80

**Comment by Tron-Creeper2** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/94975374/177004856-315f0b4f-d071-4b1a-a645-0ead4f5d2de8.png)

**Comment by versaceLORD** [comment]
Hi, please open your Task Manager and double check the details tab.
It might be that the title of the tab and the name of the process is not the same.
